apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: "3.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    args:
      - --kubelet-insecure-tls
