---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway-crds
  namespace: envoy-gateway-system
spec:
  interval: 24h
  url: oci://docker.io/envoyproxy/gateway-crds-helm
  ref:
    semver: "1.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-crds
  namespace: envoy-gateway-system
spec:
  releaseName: envoy-gateway-crds
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway-crds
  values:
    crds:
      gatewayAPI:
        enabled: false
      envoyGateway:
        enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gateway-helm
  namespace: envoy-gateway-system
spec:
  interval: 24h
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    semver: "1.x"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  releaseName: envoy-gateway
  dependsOn:
    - name: envoy-gateway-crds
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: OCIRepository
    name: gateway-helm
