---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: envoy-gateway-system
spec:
  interval: 24h
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    semver: "1.x"
  sparseCheckout:
    - config/crd/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: envoy-gateway-system
spec:
  interval: 24h
  retryInterval: 5m
  timeout: 3m
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: ./config/crd/experimental
