---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-local
spec:
  ca:
    secretName: local-ca-tls
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: liuxue1990@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
