apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    redis:
      enabled: true
      repository: public.ecr.aws/docker/library/redis
      tag: 8.6.2
    httpRoute:
      enabled: true
      parentRefs:
        - name: envoy
          namespace: envoy-gateway-system
          sectionName: http
      hostnames:
        - podinfo.local
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
