name: test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: fluxcd/flux-schema/actions/setup@main
      - uses: fluxcd/flux-schema/actions/validate@main
        with:
          path: "."
          schema-location: |
            default
            https://raw.githubusercontent.com/datreeio/CRDs-catalog/main
